/* Auto-generated from memtypes.c by gawk. */
/* Do not edit! */

#ifndef _QUAGGA_MEMTYPES_H
#define _QUAGGA_MEMTYPES_H

enum
{
  MTYPE_TMP = 1,
  MTYPE_STRVEC,
  MTYPE_VECTOR,
  MTYPE_VECTOR_INDEX,
  MTYPE_LINK_LIST,
  MTYPE_LINK_NODE,
  MTYPE_THREAD,
  MTYPE_THREAD_MASTER,
  MTYPE_THREAD_STATS,
  MTYPE_VTY,
  MTYPE_VTY_OUT_BUF,
  MTYPE_VTY_HIST,
  MTYPE_BUFFER,
  MTYPE_BUFFER_DATA,
  MTYPE_STREAM,
  MTYPE_STREAM_DATA,
  MTYPE_STREAM_FIFO,
  MTYPE_HASH,
  MTYPE_HASH_BACKET,
  MTYPE_HASH_INDEX,
  MTYPE_DESC,
  MTYPE_KEY,
  MTYPE_SOCKUNION,
  MTYPE_ZLOG,
  MTYPE_ZCLIENT,
  MTYPE_HOST,
  MTYPE_RTADV_PREFIX,
  MTYPE_NEXTHOP,
  MTYPE_VTYSH_CONFIG,
  MTYPE_VTYSH_CONFIG_LINE,
  MTYPE_MAX,
};

#endif 
